[package]
name = "rust-torrent"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
env_logger = "0.11"
hex = "0.4.3"
log = "0.4"
reqwest = { version = "0.13.1", features = ["blocking"] }
sha1 = "0.10.6"
urlencoding = "2.1.3"
